import type { Metadata } from "next";
import { Geist, Geist_Mono, Karla } from "next/font/google";
import "./globals.css";
import GlassFilters from "@/components/GlassFilters";
import PhoneFrame from "@/components/PhoneFrame";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${karla.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GlassFilters />
        <main className="flex min-h-screen items-center justify-center bg-neutral-200 p-8">
          <PhoneFrame>{children}</PhoneFrame>
        </main>
      </body>
    </html>
  );
}
