import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Karla } from "next/font/google";
import "./globals.css";
import GlassFilters from "@/components/GlassFilters";
import PhoneFrame from "@/components/PhoneFrame";
import MobileUnsupportedNotice from "@/components/MobileUnsupportedNotice";
import ReplayButton from "@/components/ReplayButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// iOS's own system font is SF Pro, which isn't available on Google Fonts —
// Inter is the closest free match, used only for the simulated status bar's
// clock so it reads as native chrome rather than the app's own Karla type.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${karla.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GlassFilters />
        <MobileUnsupportedNotice />
        <main className="hidden min-h-screen items-center justify-center gap-6 bg-neutral-200 p-8 md:flex">
          <ReplayButton />
          <PhoneFrame>{children}</PhoneFrame>
        </main>
      </body>
    </html>
  );
}
